return {
  "nvim-treesitter/nvim-treesitter",
  event = { "BufReadPre", "BufNewFile" },
  build = ":TSUpdate",
  dependencies = {
    "windwp/nvim-ts-autotag",
  },
  config = function()
    local ts = require("nvim-treesitter.configs")

    ts.setup({
      highlight = { enable = true },

      indent = { enable = true },

      autotag = { enable = true },

      ensure_installed = {
        "lua",
        "bash",
        "comment",
        "csv",
        "css",
        "diff",
        "dockerfile",
        "dot",
        "func",
        "git_config",
        "git_rebase",
        "gitattributes",
        "gitcommit",
        "gitignore",
        "go",
        "gomod",
        "gosum",
        "gowork",
        "gpg",
        "graphql",
        "groovy",
        "hcl",
        "helm",
        "hjson",
        "hlsl",
        "html",
        "http",
        "javascript",
        "ini",
        "jsdoc",
        "jq",
        "json",
        "json5",
        "jsonc",
        "luadoc",
        "markdown",
        "markdown_inline",
        "mermaid",
        "nix",
        "passwd",
        "perl",
        "php",
        "pod",
        "prisma",
        "pug",
        "python",
        "regex",
        "ruby",
        "rust",
        "scheme",
        "scss",
        "slang",
        "sql",
        "ssh_config",
        "terraform",
        "toml",
        "tsx",
        "tsv",
        "typescript",
        "vim",
        "vue",
        "xml",
        "yaml",
      },

      incremental_selection = {
        enable = true,
        keymaps = {
          init_selection = "<C-space>",
          node_incremental = "<C-space>",
          scope_incremental = false,
          node_decremental = "<bs>",
        },
      },
    })
  end,
}
